version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - run:
          name: Upgrade pip
          command: pip install --upgrade pip
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest unit_tests.py

workflows:
  version: 2
  build:
    jobs:
      - build
